### ISSUE TITLE
Not working, any setup steps? BTW much needed extension 🙌🏻

### ISSUE THREAD

**Issue by rahulbanthia** [simenko-redvike/sails-code-navigator#1]

**Comment by simenko-redvike** [comment]
There is a config allowing you to set folders in which the extension will look for the definitions, assuming that filename===moduleName. The defaults are for Sails default folder structure - `api/models` and  `api/services` - maybe your setup is different.

You can take a look at console output in VSCode DevTools (extension messages are prefixed with `SailsCodeNavigator:`).  If the log says "error loading definitions" then the reason is probably wrong config.

**Comment by rahulbanthia** [comment]
Hey @simenko-redvike!
Found out the issue, I had another folder open in the workspace (for frontend), for which the extension was failing to load, and I guess after that it didn't load for the Sails project as well.
After I saw the logs, I tried opening the Sails project in a different window, which now opens like a charm!

Thank you so much for this, and for the extension too!
